server:
  port : 8081

logging:
  level.org:
    springframework: INFO
    hibernate: DEBUG


spring:
  jpa:
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate.ddl-auto: none
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/test?user=postgres&password=cylon165
